# Generated by Django 6.0.2 on 2026-06-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentExercise',
        ),
    ]
