# Generated by Django 5.2 on 2025-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
