# Generated by Django 5.2 on 2025-10-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0002_studentexercise_additional_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentExercise',
        ),
    ]
