# Generated by Django 5.2 on 2025-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexercise',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
