# Generated by Django 5.2 on 2025-10-31 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_course_is_new_course_is_popular_course_is_public_and_more'),
        ('admin_dashboard', '0018_fix_null_scores'),
        ('student_dashboard', '0005_alter_studentexercise_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAccessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('max_session_time', models.IntegerField(default=600)),
                ('max_lessons_access', models.IntegerField(default=3)),
                ('allowed_courses', models.ManyToManyField(blank=True, to='accounts.course')),
            ],
            options={
                'verbose_name_plural': 'Guest Access Settings',
                'db_table': 'guest_access_settings',
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('time_used', models.IntegerField(default=0)),
                ('max_session_time', models.IntegerField(default=600)),
                ('timer_started', models.DateTimeField(blank=True, null=True)),
                ('accessed_lessons', models.ManyToManyField(blank=True, to='admin_dashboard.lesson')),
            ],
            options={
                'db_table': 'guest_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
