# Generated by Django 5.2 on 2025-11-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0006_guestaccesssettings_guestsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestsession',
            name='timer_started',
        ),
    ]
