# Generated by Django 5.2 on 2025-11-15 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0018_fix_null_scores'),
        ('student_dashboard', '0008_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='lesson',
            field=models.ForeignKey(default=273, on_delete=django.db.models.deletion.CASCADE, related_name='student_certificate_lesson', to='admin_dashboard.lesson'),
            preserve_default=False,
        ),
    ]
