# Generated by Django 5.2 on 2025-11-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0011_replyreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_replies', to='student_dashboard.reply'),
        ),
    ]
