# Generated by Django 5.2 on 2025-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0012_reply_additional_data_reply_parent_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
