# Generated by Django 6.0.2 on 2026-06-02 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_autoapprovalsettings_course_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.JSONField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('video_source', models.CharField(choices=[('local', 'Local File'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('cloud', 'Cloud Storage'), ('external', 'External URL')], default='local', help_text='Source of the video content', max_length=20)),
                ('video_format', models.CharField(choices=[('mp4', 'MP4'), ('webm', 'WebM'), ('ogg', 'OGG'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct File'), ('embedded', 'Embedded')], default='mp4', help_text='Video format for proper handling', max_length=20)),
                ('video_codec', models.CharField(blank=True, max_length=20)),
                ('video_bitrate', models.IntegerField(blank=True, null=True)),
                ('video_requirements', models.JSONField(blank=True, default=dict, help_text='Video completion requirements')),
                ('video_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('video_file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('supports_streaming', models.BooleanField(default=True)),
                ('requires_authentication', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_progress', models.IntegerField(default=0, help_text='Video progress in seconds')),
                ('video_duration', models.IntegerField(default=0, help_text='Total video duration in seconds')),
                ('video_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Total time spent in seconds')),
                ('session_count', models.IntegerField(default=0, help_text='Number of learning sessions')),
                ('engagement_data', models.JSONField(blank=True, default=dict)),
                ('watch_patterns', models.JSONField(blank=True, default=list)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'last_accessed'], name='lessons_les_student_0a9d34_idx'), models.Index(fields=['lesson', 'video_completed'], name='lessons_les_lesson__93ece5_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='VideoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_viewers', models.IntegerField(default=0)),
                ('total_watch_time', models.IntegerField(default=0, help_text='Total seconds watched')),
                ('average_engagement_score', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('analytics_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analytics', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('lesson', 'date')},
            },
        ),
    ]
