# Generated by Django 5.2 on 2025-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_course_teacher_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='DCB', max_length=7),
            preserve_default=False,
        ),
    ]
