# Generated by Django 5.2 on 2025-09-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='student',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
