# Generated by Django 5.2 on 2025-11-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_course_is_new_course_is_popular_course_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Personal Development', 'Personal Development'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Department of Education', 'Department of Education')], default='Personal Development', max_length=50),
        ),
    ]
