# Generated by Django 5.2 on 2025-08-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexercise',
            name='lesson',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.lesson'),
        ),
    ]
