# Generated by Django 5.2 on 2025-08-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_alter_studentexercise_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.lesson'),
        ),
    ]
