# Generated by Django 5.2 on 2025-08-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_revenuereport_teacherpayout_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hosting_fee_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
