# Generated by Django 5.2 on 2025-09-10 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_alter_lesson_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='exercise_attempts',
            field=models.JSONField(default=dict, help_text='Track attempts per exercise'),
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Time spent on exercises in seconds'),
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentexercise',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterModelTable(
            name='studentexercise',
            table='admin_dashboard_studentexercise',
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_progress', models.IntegerField(default=0, help_text='Video progress in seconds')),
                ('video_completed', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(default=0, help_text='Total time spent in seconds')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('video_play_count', models.IntegerField(default=0)),
                ('exercise_attempts', models.JSONField(default=dict, help_text='Track individual exercise attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='admin_dashboard.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_dashboard_lessonprogress',
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='LessonUnderstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understanding_text', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_understandings', to='admin_dashboard.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_understandings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_dashboard_lessonunderstanding',
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
