# Generated by Django 5.2 on 2025-09-16 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0013_studentexercise_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='exercise_attempts',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='video_play_count',
        ),
        migrations.RemoveField(
            model_name='studentexercise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentexercise',
            name='exercise_attempts',
        ),
        migrations.RemoveField(
            model_name='studentexercise',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='studentexercise',
            name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='studentexercise',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='studentexercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exercises_admin_dashboard', to='admin_dashboard.lesson'),
        ),
        migrations.AlterField(
            model_name='studentexercise',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexercise',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='lessonprogress',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentexercise',
            table=None,
        ),
        migrations.DeleteModel(
            name='LessonUnderstanding',
        ),
    ]
