# Generated by Django 5.2 on 2025-09-23 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0014_remove_lessonprogress_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_viewers', models.IntegerField(default=0)),
                ('total_watch_time', models.IntegerField(default=0, help_text='Total seconds watched')),
                ('average_engagement_score', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0, help_text='Percentage of viewers who completed')),
                ('analytics_data', models.JSONField(blank=True, default=dict, help_text='Detailed analytics: drop-off points, replay sections, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Video completion requirements: min_watch_percentage, min_engagement_score, etc.'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='engagement_data',
            field=models.JSONField(blank=True, default=dict, help_text='Engagement analytics: watch patterns, interaction data, etc.'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='session_count',
            field=models.IntegerField(default=0, help_text='Number of learning sessions'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='video_duration',
            field=models.IntegerField(default=0, help_text='Total video duration in seconds'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_patterns',
            field=models.JSONField(blank=True, default=list, help_text='Detailed watching patterns and segments'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['student', 'last_accessed'], name='admin_dashb_student_348de3_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'video_completed'], name='admin_dashb_lesson__718407_idx'),
        ),
        migrations.AddField(
            model_name='videoanalytics',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analytics', to='admin_dashboard.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='videoanalytics',
            unique_together={('lesson', 'date')},
        ),
    ]
