# Generated by Django 5.2 on 2025-10-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_grade_course_remove_grade_student_and_more'),
        ('admin_dashboard', '0015_videoanalytics_lesson_video_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_authentication',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='supports_streaming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_codec',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_format',
            field=models.CharField(choices=[('mp4', 'MP4'), ('webm', 'WebM'), ('ogg', 'OGG'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct File'), ('embedded', 'Embedded')], default='mp4', help_text='Video format for proper handling', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_source',
            field=models.CharField(choices=[('local', 'Local File'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('cloud', 'Cloud Storage'), ('external', 'External URL')], default='local', help_text='Source of the video content', max_length=20),
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='submission_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='accounts.course'),
        ),
    ]
