# Generated by Django 5.2 on 2025-10-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0016_lesson_allow_download_lesson_requires_authentication_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentExercise',
        ),
    ]
